#!/bin/bash

set -e +x -o pipefail

# Set the TGT to identify the OS and version.
TGT=$(source /etc/os-release; echo "${ID}-${VERSION_ID}")
# e.g. ubuntu-22.04, ubuntu-24.04, debian-11, rocky-9.7, rocky-9.5, rocky-10.1 etc.
distro_unsupported()
{
    echo "Unsupported distro $TGT" >&2
    exit 1
}
version_unsupported()
{
    echo "Unsupported distro version $TGT" >&2
    exit 1
}

# Detect unsupported distribution early.
if [[ ! "$TGT" =~ rocky|ubuntu ]]; then
    distro_unsupported
fi


configure_base()
{
    case "$TGT" in
        rocky*)
            PKGS=(
                ImageMagick
                ImageMagick-devel
                glibc-langpack-en
                mercurial
            )
            case "$TGT" in
                *9.*)
                    PKGS+=(libyaml-devel)
                ;;
                *10.*)
                    # fallback: libyaml-devel package is unavailble on rocky10
                    PKGS+=(libyaml)
                ;;
                *)
                    version_unsupported
                ;;
            esac
            yum install -y yum-utils
            dnf install -y dnf-plugin-config-manager
            dnf config-manager --enable crb
            dnf install -y epel-release
            dnf update -y

            dnf -y install ${PKGS[@]}
            dnf remove -y epel-release yum-utils

            dnf -y autoremove
            dnf clean all
        ;;
        ubuntu*)
            # Make noninteractive setting permanent
            export DEBIAN_FRONTEND=noninteractive
            echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections -v
            apt update
        ;;
        *)
            distro_unsupported
        ;;
    esac
}


configure_sshkeys()
{
    # Create busybee credentials and make busybee pkey available for root
    mkdir -p /root/.ssh
    chmod 700 /root/.ssh
    # The below commands depend on the dockerfile copying the ssh key pair
    # to /tmp before this script is executed.
    mv /tmp/busybee* /root/.ssh
    cat /root/.ssh/busybee.pub >>/root/.ssh/authorized_keys
    chmod 600 /root/.ssh/busybee

    case "$TGT" in
        rocky*)
            ssh-keygen -t ed25519 -N '' -f /etc/ssh/ssh_host_ed25519_key
        ;;
        ubuntu*)
            # noop
            true
        ;;
        *)
            distro_unsupported
        ;;
    esac

    # 1. permit root logins and set simple password password and pubkey
    # 2. change requiretty to !requiretty in /etc/sudoers
    sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
    sed -ri 's/^#?PubkeyAuthentication\s+.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
    sed -ri 's/requiretty/!requiretty/' /etc/sudoers
    echo 'root:docker.io' | chpasswd

    mkdir /var/run/sshd
}

install_locale()
{
    case "$TGT" in
        rocky*)
            PKGS=(
                nc
                net-tools
                glibc-locale-source
            )
            dnf -y install ${PKGS[@]}
            dnf -y autoremove; dnf clean all

            # -i: specify the locale definition file
            # -f: specify the character set
            localedef -i en_US -f UTF-8 en_US.UTF-8
        ;;
        ubuntu*)
            # install locales package and set default locale to
            # 'UTF-8' for the test execution environment.
            apt-get -y install locales
            locale-gen en_US.UTF-8
            dpkg-reconfigure locales
            update-locale LANG=en_US.UTF-8
        ;;
        *)
            distro_unsupported
        ;;
    esac
}

install_download_tools()
{
    case "$TGT" in
        rocky*)
            PKGS=(
                ca-certificates
                iproute
                nc
                net-tools
                procps
                setup
                subversion
                wget
            )
            dnf -y install ${PKGS[@]}
            # work around package manager confusion when installing curl.
            dnf -y --allowerasing install curl
            dnf -y autoremove; dnf clean all
        ;;
        ubuntu*)
            PKGS=(
                ca-certificates
                apt-transport-https
                gdebi-core
                sshpass
                cron
                curl
                wget
                netcat-traditional
                net-tools
                iproute2
                netbase
            )
            apt -y install ${PKGS[@]}
            apt clean
        ;;
        *)
            distro_unsupported
        ;;
    esac
}

configure_testing_system()
{
    case "$TGT" in
        rocky*)
            cd /lib/systemd/system/sysinit.target.wants/
            ls -1 | grep -v systemd-tmpfiles-setup.service | xargs rm
            rm -f /etc/systemd/system/*.wants/*
            rm -f /lib/systemd/system/local-fs.target.wants/*
            rm -f /lib/systemd/system/sockets.target.wants/*udev*
            rm -f /lib/systemd/system/sockets.target.wants/*initctl*
            rm -f /lib/systemd/system/basic.target.wants/*
            rm -f /lib/systemd/system/anaconda.target.wants/*
            systemctl preset sshd

            # install doc files (/usr/share/docs) when installing yum packages
            # otherwise /usr/share/docs/st2/conf/nginx/st2.conf won't be present
            # https://github.com/docker-library/docs/tree/master/centos#package-documentation
            sed -i '/nodocs/d' /etc/yum.conf
        ;;
        ubuntu*)
            # TO DO: This may be a pre-systemd relica.
            find /etc/systemd/system \
                 /lib/systemd/system \
                 -path '*.wants/*' \
                 -not -name '*journald*' \
                 -not -name '*systemd-tmpfiles*' \
                 -not -name '*systemd-user-sessions*' \
                 -exec rm \{} \;

            systemctl set-default multi-user.target

            # The base Ubuntu 18.04 image contains a file that excludes
            # all documentation from being installed by packages.
            # Specifically /usr/share/doc/* This exclusion prevents our
            # nginx config from being installed in the 'st2' package:
            # /usr/share/doc/st2/conf/nginx/st2.conf
            # This step removes the exclusion configuration so
            # documentation of all future packages will be installed.
            rm -rf /etc/dpkg/dpkg.cfg.d/excludes
        ;;
        *)
            distro_unsupported
        ;;
    esac
}

install_system_tools()
{
    case "$TGT" in
        rocky*)
            PKGS=(
                git
                openssh-server
                openssh-clients
                sudo
            )
            ls /etc/crypto-policies/policies/modules/
            dnf -y install ${PKGS[@]}
            dnf -y autoremove; dnf clean all
        ;;
        ubuntu*)
            PKGS=(
                git
                openssh-server
                sudo
            )
            apt -y install ${PKGS[@]}
        ;;
        *)
            distro_unsupported
        ;;
    esac

    configure_sshkeys
}


install_build_dependencies()
{
    case "$TGT" in
        rocky*)
            PKGS=(
                autoconf
                automake
                bzip2
                bzip2-devel
                file
                gcc
                gcc-c++
                glib2-devel
                glibc-devel
                libcurl-devel
                libevent-devel
                libffi-devel
                libjpeg-devel
                libtool
                libwebp-devel
                libxml2-devel
                libxslt-devel
                make
                ncurses-devel
                openssl-devel
                pam
                patch
                postgresql-devel
                readline-devel
                sqlite-devel
                unzip
                xz
                xz-devel
                zip
                zlib-devel
            )
            case "$TGT" in
                *9.*)
                    PKGS+=(mysql-devel)
                ;;
                *10.*)
                    # rocky10 includes the version number in mysql-devel package name.
                    PKGS+=(mysql8.4-devel)
                ;;
                *)
                    version_unsupported
                ;;
            esac
            dnf -y install ${PKGS[@]}
            dnf -y autoremove; dnf clean all
        ;;
        ubuntu*)
            PKGS=(
                build-essential
                python3-venv
                python3-setuptools
                python3-mock
                python3-sphinx
                dh-exec
                dh-python
                dh-virtualenv
                libjs-jquery
                libjs-underscore
                python3-sphinx-rtd-theme
            )
            apt -y install ${PKGS[@]}
            apt clean

            # Use upstream dh-virtualenv master branch that includes StackStorm's
            # 'python' shebang fix since 8 Dec 2020.  We reset the repository to
            # use the known good commit sha id 9bd6d3fac3ea9b53e12bfedeef53f0a73c57b2cd
            ##git clone --branch master https://github.com/spotify/dh-virtualenv.git /tmp/dh-virtualenv
            ##cd /tmp/dh-virtualenv
            ##git reset --hard 9bd6d3fac3ea9b53e12bfedeef53f0a73c57b2cd
            ##dpkg-buildpackage -b -uc -us && dpkg -i ../dh-virtualenv_*.deb
            ##rm -rf /tmp/dh-virtualenv*
            # apt -y install dh-systemd && apt clean
        ;;
        *)
            distro_unsupported
        ;;
    esac
}


install_st2_build_dependencies()
{
    case "$TGT" in
        rocky*)
            PKGS=(
                openldap-devel
            )
            dnf -y install ${PKGS[@]}
            dnf -y autoremove; dnf clean all
        ;;
        ubuntu*)
            PKGS=(
                devscripts
                debhelper
                dh-make
                libldap2-dev
                libsasl2-dev
            )
            apt -y install ${PKGS[@]}
            apt clean
            ;;
        *)
            distro_unsupported
        ;;
    esac
}


install_python()
{
    # Python packages installed for all distribution types.
    COMMON_PYPKGS=(
        "virtualenv==21.5.1"
        "pip==26.1.2"
        "setuptools==82.0.1"
        "wheel==0.45.1"
        build
    )
    case "$TGT" in
        rocky*)
            case "$TGT" in
                *9.*)
                    # St2 v3.10 supports py3.11
                    PKGS+=(
                        python3.11
                        python3.11-devel
                        python3.11-pip
                        python3.11-setuptools
                        rpmdevtools
                    )
                    # Set py3.11 as default python3 interpreter for the system
                    export PYBIN=python3.11
                    export PIPBIN=pip3.11
                    # disable to see if the package build works correctly.

                    dnf -y install ${PKGS[@]}
                    dnf -y autoremove; dnf clean all
                ;;
                *10.*)
                    # Py3.12 is default on rocky10
                    PKGS+=(
                        python3
                        python3-devel
                        python3-setuptools
                        rpmdevtools
                    )
                    export PYBIN=python3.12
                    export PIPBIN=pip3.12
                    dnf -y install ${PKGS[@]}
                    dnf -y autoremove; dnf clean all
                ;;
                *)
                    version_unsupported
                ;;
            esac
            echo "PYTHON/PIP VERSION"
            $PYBIN --version
            $PIPBIN --version

            PYPKGS=(${COMMON_PYPKGS[@]})

            $PIPBIN install --upgrade ${PYPKGS[@]}
            rm -rf /root/.cache
        ;;
        ubuntu*)
            # install python development
            PKGS=(
                python3-dev
                python3
                python3-pip
            )
            apt -y install ${PKGS[@]}
            apt clean
            # Install fresh pip and co (pinning wheel and setuptools<60 is
            # require for dh-virtualenv build to avoid pypa/setuptools#2956)
            PYPKGS=(${COMMON_PYPKGS[@]})
            PYPKGS+=(
                cryptography
                "requests[security]"
            )
            # Violate system package manager and force our requirements ...  Leroy Jenkins!
            case "$TGT" in
                *22.*)
                    apt install --only-upgrade python3-pip
                    pip3 install --ignore-installed --upgrade ${PYPKGS[@]}
                ;;
                *24.*)
                    apt install --only-upgrade python3-pip
                    pip3 install --ignore-installed --break-system-packages --upgrade ${PYPKGS[@]}
                ;;
                *)
                    version_unsupported
                ;;
            esac
            rm -rf /root/.cache
        ;;
        *)
            distro_unsupported
        ;;
    esac
}


compare_operations()
{
    test -n "$1" && test -n "$2" && test "$1" = "$2"
}
run()
{
    # Permitted operation calls to be run from docker build.
    ALLOWED_OPS=(
        configure_base
        install_download_tools
        install_system_tools
        install_python
        install_build_dependencies
        install_st2_build_dependencies
        install_locale
        configure_testing_system
    )
    OP="$1"
    EXEC=0
    for ALLOWED_OP in ${ALLOWED_OPS[@]}
    do
        if compare_operations "$OP" "$ALLOWED_OP"; then
            "$1"
            EXEC=1
        fi
    done
    if [[ $EXEC -eq 0 ]]; then
        echo "Operation $1 failed to be executed!"
        exit 1
    fi
}

run "$1"
